### ISSUE TITLE
Build error on step 42 - npm version

### ISSUE THREAD

**Issue by ghost** [chriswhong/docker-cartodb#20]
Coming up against this on Ubuntu 14.04.4 LTS:

`Running "cdb" task`
`Installed npm version does not match with required [3.10.9] Installed: 2.14.9`
`Fatal error: grunt is not defined`
`The command '/bin/sh -c cd cartodb &&    npm install npm@2.14.9 -g &&    npm -v &&    export PATH=$PATH:$PWD/node_modules/grunt-cli/bin &&    bundle install &&    bundle exec grunt --environment production' returned a non-zero code: 3`

**Comment by thadk** [comment]
I noticed that the team seems to have switched to Node 6 and may be using `yarn`:
https://groups.google.com/forum/#!topic/cartodb/KJlt4wK3mEg

Here is [a new PPA](https://launchpad.net/~cartodb/+archive/ubuntu/nodejs), but I couldn't get it working with 12.04:

```The following packages have unmet dependencies:
 nodejs : Depends: libstdc++6 (>= 4.9) but 4.6.3-1ubuntu5 is to be installed
``` 
EDIT: see the https://launchpad.net/~cartodb/+archive/ubuntu/gcc reference in the latest instructions: http://cartodb.readthedocs.io/en/latest/install.html

I also had trouble with `thin` and `rack` installation via the Ruby Gem bundler but commented that step out until I resolved the NodeJS issue.
```
Downloading thin-1.7.0 revealed dependencies not in the API or the lockfile
(rack (< 3, >= 1)).
Either installing with `--full-index` or running `bundle update thin` should fix
the problem.
The command '/bin/sh -c cd cartodb &&    npm install npm@2.14.9 -g &&    npm -v &&    export PATH=$PATH:$PWD/node_modules/grunt-cli/bin &&    bundle install &&    bundle exec grunt --environment production' returned a non-zero code: 34
```

Also now the Dec 2016 version of Windshaft has trouble with the new v6 nodejs. What was the goal of selecting that version? -- ah I see it was a temporary issue with master.

**Final edit for now**: I found an older image on my machine that was built when this Dockerfile was working so I've given up for now but I made a huge amount of progress. It will likely be useful for anyone trying to modernize this repository. Here is my final Dockerfile: https://github.com/thadk/docker-cartodb/blob/master/Dockerfile (see the "Blame" for my alterations)

I was able to get to the grunt execution but it fails because it is missing the `bundle install`. It is possible you could back up the version of cartodb from master to a slightly previous release and the Gem error with `thin` and `rack` would be resolved, or it may be resolved by the time you read this.

**Comment by mgottholsen** [comment]
Has anyone had any success with this?

**Comment by azvoleff** [comment]
I addressed the issue with thin by using thin-1.7.2 (installed by removing `Gemfile.lock`). But of course then the consistency of installs across multiple machines isn't guaranteed as packages are updated.

Should have mentioned I am using Ubuntu 16.04, not 12.04.

**Comment by thadk** [comment]
I believe this issue is resolved -- get the new version https://github.com/chriswhong/docker-cartodb/pull/22 while its hot.

**Comment by chriswhong** [comment]
Indeed, this is no longer an issue with the latest changes in #22
